server:
  port: 7001

eureka:
  instance:
    appname: eureka7001.com
  client:
    register-with-eureka: false  #eureka server 本身不用注册进服务列表
    fetch-registry: false          #不进行检索
    service-url:
      #defaultZone: http://${eureka.instance.appname}:${server.port}/eureka/ 单机版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/