server:
  port: 80

deptservice:
  prefix: http://MICROSERIVECLOUD-DEPT

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #eureka集群版 将服务注册到eureka服务中
