server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #eureka集群版 将服务注册到eureka服务中
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: fly-microserivecloud
  company.name: www.fly.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
zuul:
  routes:
    mydept.serviceId: microserivecloud-dept
    mydept.path: /mydept/**                 #别名
  ignored-services: "*"                     #禁止通过服务名称进行访问服务
  prefix: /fly                              #统一前缀设置